import { runEntire } from ".";
import fs from 'fs';

let data = fs.readFileSync('dataSet.txt', 'utf-8').toLowerCase().split(/\s+|\n+/g);
let randomContext = data[Math.floor(Math.random() * data.length)];

let quote = runEntire(randomContext.split(' '));
let file = `\`"${quote}"\`\n\nGenerated at ${new Date().toLocaleString()}\n\n**Anything generated by this program is not to be taken seriously, and is purely for entertainment purposes.**`;

fs.writeFileSync('readme.md', file);